services:
  tunnel:
    build:
      context: .
      dockerfile: Dockerfile.tunnel-only
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TUNNEL_ORIGIN_CERT=/etc/cloudflared/cert.pem
      - NO_AUTOUPDATE=true
    # Isolated network
    networks:
      - monaco-tunnel-network

networks:
  monaco-tunnel-network:
    driver: bridge
